### ISSUE TITLE
Version 0.0.2

### ISSUE THREAD

**Issue by TheTVExpert** [TheTVExpert/rmCloser#1]
- [x] Confirmation for relisting (#2) (Implemented early)
- [x] Implement move (#8)
- [x] Add old move to all talkpages (#4)
- [x] Notify WikiProjects (#7)
- [x] Add old move before archives (#5)
- [x] Make input required for custom result (#6)
