### ISSUE TITLE
Version 0.0.3

### ISSUE THREAD

**Issue by TheTVExpert** [TheTVExpert/rmCloser#10]
- [x] Disable on non-talk pages, pages not in Requested moves category, and old revisions (#12) (Implemented as 0.0.3 A)
- [x] Hide Notify WikiProjects button when confirming relist (#12) (Implemented as 0.0.3 A)
- [x] Add Feedback link (#12) (Implemented as 0.0.3 A)
- [x] Add closing comment (#12) (Implemented as 0.0.3 A)
- [x] Don't close if no result is selected (#13) (Implemented as 0.0.3 B)
- [x] Make selecting a WikiProject required when notifying (#14) (Implemented as 0.0.3 B)
- [x] Don't add destination to old move if it is a question mark (#15) (Implemented as 0.0.3 C)
- [x] Add a note at the requested move when notifying a WikiProject (#15) (Implemented 0.0.3 C)
